### ISSUE TITLE
Versioning Consistancy

### ISSUE THREAD

**Issue by declan-fitzpatrick** [thehamsterjam/better_aws_sso#3]
## Problem
The versioning currently can de-synchronize because there are two different places where the versions are entered. This will cause the update script to soft-fail, and download a new version.

They are entered when a tag is created for the repo, and in the [main.rs](https://github.com/thehamsterjam/better_aws_sso/blob/470292eafc6ab4d80739467d74c857d45df03c72/src/main.rs#L61) file.

## Proposed Fix
Consider changing the line in [main.rs](https://github.com/thehamsterjam/better_aws_sso/blob/470292eafc6ab4d80739467d74c857d45df03c72/src/main.rs#L61) with an API call to the GitHub API. 
[linux_install.sh](https://github.com/thehamsterjam/better_aws_sso/blob/470292eafc6ab4d80739467d74c857d45df03c72/install/linux_install.sh#L23) is already doing this: 

```shell
$ LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/thehamsterjam/better_aws_sso/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
```
The install script then compares the `LATEST_RELEASE` to the release named by the `ssologin -V` command. If these are identical, the update is skipped. 
If they differ, the latest release is downloaded. 

The above would API call will need to be converted to rust. For reference, a Python implementation looks like: 
```python
def get_latest_release(repo):
    # https://developer.github.com/v3/repos/releases/
    api_root = "https://api.github.com/"

    request_header = {'Accept':'application/vnd.github.v3+json'}
    request = api_root + "repos/" + GITHUB_REPO_OWNER + "/" + repo + "/releases/latest"
    # response = requests.get(request, headers = request_header, auth=requests.auth.HTTPBasicAuth(GITHUB_API_USER, GITHUB_API_APP_PASSWORD)).json() ## this line includes auth headers, which are required for private repos only. 
    response = requests.get(request, headers = request_header).json()
    try: 
        tag_name = response["tag_name"]
        if not "v" in tag_name: tag_name = "v" + tag_name # make sure the tag name is of the form vX.X.X
        return tag_name
    except: 
        print("For '" + repo + "', there was an error getting the tag from the api: " + str(response))
        return "n/a"
```

## Outcome
This change would mean that all builds would pull in the latest tag and add them to the `main.rs` file. Meaning that tags would be consistant. 

## Possible Future Errors
By always pulling latest, any builds that are not release builds (which are triggered when a new tag is created) will have the incorrect version. The maintainer may decide on how much impact that has on the dev and testing process.

**Comment by thehamsterjam** [comment]
This would have to be done in the cargo build script along with an `include_str!`(see https://stackoverflow.com/questions/32956050/how-to-create-a-static-string-at-compile-time)

I am sure you could make a pull request.
